@startuml
skinparam Monochrome true
skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "I2S Acquisition Thread" #F9F9F9
participant "recorder_thread_i2s" as I2S
participant "I2S Hardware" as HW
end box

box "Storage Thread" #F4F4F4
participant "recorder_thread_store_to_file" as Store
participant "sdcard.c" as SD
end box

participant "BLE Handler" as BLE

== Initialization ==

I2S -> SD : sdcard_file_init()
I2S -> I2S : recorder_i2s_initialize()
I2S -> I2S : recorder_configure_streams()
I2S -> BLE : ble_update_status(ST_IDLE)

== Phase 1: Wait for recording trigger ==

I2S -> I2S : k_sem_take(recorder_toggle_transfer_sem, K_FOREVER)
note right: Triggered by button or BLE
activate I2S
I2S -> BLE : ble_update_status(ST_RECORDING)

== Phase 2: Calibration & wait for saving ==

I2S -> I2S : recorder_calibration()

loop while is_recorder_enable
    I2S -> I2S : k_poll(rec_events, K_FOREVER)
    note right: Poll toggle saving and transfer semaphore\nCPU sleeps until trigger
    
    == Phase 3: Data acquisition (saving loop) ==
    alt Toggle saving signaled
        I2S -> HW : i2s_trigger(I2S_TRIGGER_START)
        
        loop while is_saving_enable AND !force_stop_recording
            I2S -> HW : i2s_read(mem_block)
            HW --> I2S : Audio Data (24-bit)
            
            I2S -> I2S : recorder_normalize_sample()
            I2S -> I2S : Copy to store_block[write_idx]
            
            alt store_block is full
                I2S -> I2S : Swap Buffers
                I2S -> Store : k_sem_give(recorder_file_access_sem)
                note right: This interaction is detailed in the sequence diagram\nrecorder-file-saving-sequence-diagram.puml.
            end
        end
        
        == Stop saving / back to record mode ==
        alt file open
            I2S -> I2S : Swap Buffers
            I2S -> Store : k_sem_give(recorder_file_access_sem)
            note right: Flush remaining data to SD
        end

        I2S -> Store : k_sem_take(&file_access_sem, K_FOREVER);
        I2S -> Store : k_sem_give(&file_access_sem);
        note right: Wait for the file closure to finish
        I2S -> HW : i2s_trigger(I2S_TRIGGER_DROP)
        I2S -> I2S : gpio_hal_force_low_i2s_gpio()

    end

== Phase 4: Termination ==
    alt Toggle transfer signaled
        I2S -> Store : k_sem_give(recorder_file_access_sem)
        I2S -> Store : k_sem_take(&file_access_sem, K_FOREVER);
        I2S -> Store : k_sem_give(&file_access_sem);
        note right: Wait for the file closure to finish
        
        I2S -> HW : i2s_trigger(I2S_TRIGGER_DROP)
        I2S -> I2S : gpio_hal_force_low_i2s_gpio()
        I2S -> BLE : ble_update_status(ST_IDLE)
        I2S -> SD : sdcard_file_close()
        alt No open collar command received
            I2S -> SD : sdcard_off_and_reset()
            note right: Back in Hardware off\n apply software reset
        end
    end
end
deactivate I2S

@enduml