@startuml

'https://plantuml.com/class-diagram

skinparam handwritten false
skinparam defaultFontName Calibri
skinparam DefaultFontSize 12
skinparam classFontStyle Light

skinparam classAttributeIconSize 10
skinparam classStereotypeFontColor Coral
skinparam classStereotypeFontStyle Italic

'skinparam nodesep 100
'skinparam ranksep 7

set namespaceSeparator ::


@enduml