@startuml
skinparam monochrome true
participant "Peer Device" as Peer
participant "BLE Scan Module\n(Zephyr)" as BLE
participant "ble_proximity.c\n(scanning_filter_match)" as Logic
participant "Flush Timer" as Timer
participant "Proximity Store\nThread" as Store
participant "SD Card" as SD

== Detection Phase ==
Peer -> BLE : BLE Advertisement\n(Manufacturer Data: 0x5A02)
BLE -> Logic : scanning_filter_match()

alt Device already seen (De-duplication)
    Logic -> Logic : Address in seen_devices list
    note right : **Ignore** record
else New Device detected
    Logic -> Logic : Add 13-byte record to RAM
    
    alt Buffer Full
        Logic -> Timer : k_work_cancel()
        Logic -> Store : Give ble_file_access_sem
        note right : Immediate rotation
    else Buffer not Full
        Logic -> Timer : k_work_reschedule()
        note right : CONFIG_BT_PROXIMITY_FLUSH_TIMEOUT_MIN
    end
end

== Timeout Logic ==
note over Logic, Timer #LightGray
    <b>No more devices detected

    RAM buffer holds partial data
end note


Timer -> Logic : proximity_flush_handler()
Logic -> Store : Give ble_file_access_sem
note right : Force write of partial buffer


== Storage ==
note over Logic, Timer #LightGray
    <b>See main ble proximity sequence

    RAM buffer holds partial data
end note
@enduml