@startuml
skinparam monochrome true
skinparam state {
  BackgroundColor<<Logic>> LightGray
}

[*] --> ST_INIT

state ST_INIT {
  state "Hardware Check" as HW_Check
  state "Mount SD Card" as SD_Mount
  
  [*] --> HW_Check
  HW_Check --> SD_Mount : OK
  SD_Mount --> [*] : Success
}

ST_INIT --> ST_IDLE : Success
ST_INIT --> ST_WAIT_SD_CARD : SD Error

state ST_WAIT_SD_CARD {
  state "Polling for SD" as SD_Poll
  [*] --> SD_Poll
  SD_Poll --> [*] : Inserted
}
ST_WAIT_SD_CARD --> ST_INIT : Retry

state ST_IDLE {
}

ST_IDLE --> ST_RECORDING : BLE "Start" Command
ST_IDLE --> ST_POWER_SAVING : Battery < 10%

state ST_RECORDING {
  state "Awaiting Wake" as AwaitingWake <<Logic>>
  state "Saving session" as Saving {
    state "Buffering" as Buff
    state "SD Write" as Write
    Buff -> Write : Buffer Full
  }
  note right of AwaitingWake : Proximity\ndetection started
  [*] --> AwaitingWake
  AwaitingWake --> Saving : MIC_WAKE Pulse
  Saving --> AwaitingWake : Tail timer
}

ST_RECORDING --> ST_DISK_FULL : No Space
ST_RECORDING --> ST_LOW_BATT : Low Voltage
ST_RECORDING --> ST_IDLE : BLE "Stop" Command

state ST_POWER_SAVING {
  note : Close Files\nMic OFF\nLow-Power Adv
}

ST_DISK_FULL --> ST_POWER_SAVING
ST_LOW_BATT --> ST_POWER_SAVING

state "COLLAR_RELEASE" as Release #LightGray
ST_RECORDING --> Release : BLE "Open Collar"
ST_IDLE --> Release : BLE "Open Collar"
ST_POWER_SAVING --> Release : BLE "Open Collar"

Release --> ST_POWER_SAVING : Pulse Done
@enduml