@startuml
skinparam monochrome true
skinparam state {
BackgroundColor<<Logic>> LightGray
}

state SLEEP_MODE {
note "I2S clk = 0Hz\nAAD A\nNo data on I2S" as N1
}

note left of SLEEP_MODE : System in recording state.\nWait for a wake signal\nto start saving session.

state LOW_POWER_MODE {
note "I2S clk = 768kHz\nAAD D1\nData on I2S" as N2
}
note left of LOW_POWER_MODE : System in recording state.\nSave data to SD.\nKeep in this mode\nby AAD D1 wake.

SLEEP_MODE --> LOW_POWER_MODE : AAD A wake
LOW_POWER_MODE --> LOW_POWER_MODE : AAD D1 wake
LOW_POWER_MODE --> SLEEP_MODE : Tail timer
@enduml