@startuml
skinparam style strictuml
skinparam monochrome true
skinparam packageStyle rectangle

participant "Main Thread" as Main
participant "BLE Handler Thread" as APP

participant "Speak No\nEvil Service" as SNES
participant "BLE Stack\n(Host/Controller)" as S
participant "nRF54L15\nRadio" as HW
participant "SIG Device\nInformation Service" as DIS
activate APP
    APP -> APP : handle_device_name()
    Main -> APP : k_sem_give(&thread_ble_busy_sem)
    note right : Wait for the Main Thread\nto finish initialization

== Phase 1 : SNES initialization ==
    APP -> SNES : bt_snes_init(&snes_cb)
    note right : Custom service initialization
    APP -> SNES : ble_update_device_id_char_val()
    APP -> SNES : ble_update_mic_gain_char_val()
    APP -> SNES : ble_update_mic_aada_params_char_val()
    APP -> SNES : ble_update_mic_aadd1_params_char_val()

== Phase 2 : BLE initialization ==
    APP -> S : bt_enable()
    activate S
    S -> HW : Init radio peripheral
    S -> HW : Set device address
    deactivate S

    APP -> S : set_ble_tx_power(+3)
    APP -> DIS : sig_dis_init()
    APP -> APP : init_scanning()
    APP -> S : bt_le_adv_start( )
    S -> HW : Tx Adv packets (Ch 37, 38, 39)
deactivate APP
@enduml