@startuml

!include ../settings.puml

skinparam ranksep 50

hide empty description
left to right direction

actor Operator as a2

package "Release Collar" {
    usecase LF [
        <b>Look for
        ----
        Starts a BLE Scan process
        to discover nearby devices
    ]
    usecase DD [
        <b>scan results
        ----
        Provides a list of
        nearby devices 
    ]
    usecase CT [
        <b>Connect To
        ----
        Connecting to the choosen
        "Speak No Evil" device
    ]
    usecase SD [
        <b>Connected
        ----
        - Start a service discovery
        - Enable mandatory notifications
    ]
    usecase OP [
       <b>Open Collar 
    ]
    usecase dis [
        <b>Disconnect
        ----
        Disconnect from device
        ....
        Running state do NOT change
    ]
}

a2 --> LF : Cmd: Scan
LF ..> DD
a2 --> CT : Select
CT ..> SD 
' SD --> a2 : Device Connected & Ready
a2 --> OP : Cmd: Open Collar
a2 --> dis : Cmd:Disconnect
' dis --> a2 : Disconnected

@enduml